// ---------------------------------------------------------------------------
// Task Planner Type Definitions — Multi-Step Goal Decomposition
// ---------------------------------------------------------------------------

/** Status of an individual step. */
export type StepStatus =
  | 'pending'
  | 'in_progress'
  | 'completed'
  | 'failed'
  | 'skipped';

/** A single step in a task plan. */
export interface TaskStep {
  /** Unique step ID (plan-scoped). */
  id: string;
  /** Step index (0-based). */
  index: number;
  /** Human-readable description of what to do. */
  description: string;
  /** Ducky Script or action to execute (generated by VLM). */
  action: string;
  /** What should be true after this step succeeds. */
  verificationCriteria: string;
  /** Current status. */
  status: StepStatus;
  /** Number of times this step has been attempted. */
  attempts: number;
  /** Maximum retries before marking failed. */
  maxRetries: number;
  /** Dependent step IDs that must complete first. */
  dependsOn: string[];
  /** Estimated screen region to interact with (normalized 0-100). */
  targetRegion?: { x: number; y: number; width: number; height: number };
  /** Step-level notes from the planner. */
  notes?: string;
  /** Timestamp of last status change. */
  updatedAt: number;
  /** Error message if failed. */
  error?: string;
}

/** A complete task plan with steps and checkpoints. */
export interface TaskPlan {
  /** Unique plan ID. */
  id: string;
  /** The high-level user goal. */
  goal: string;
  /** Ordered list of steps. */
  steps: TaskStep[];
  /** Current step index being executed. */
  currentStepIndex: number;
  /** Plan status. */
  status: 'planning' | 'executing' | 'paused' | 'completed' | 'failed' | 'replanning';
  /** Checkpoint: last successfully completed step index. */
  checkpointIndex: number;
  /** Number of times the plan has been regenerated. */
  replanCount: number;
  /** Maximum replans before giving up. */
  maxReplans: number;
  /** When the plan was created. */
  createdAt: number;
  /** When the plan was last updated. */
  updatedAt: number;
  /** Screen context when plan was created. */
  initialScreenDescription?: string;
  /** Screen classification when plan was created. */
  initialScreenType?: string;
}

/** Snapshot of the current screen state for planning context. */
export interface ScreenContext {
  /** Base64 image of the current screen. */
  imageBase64: string;
  /** CNN screen classification (if available). */
  screenType?: string;
  /** CNN-detected UI elements (if available). */
  detectedElements?: Array<{
    class: string;
    label: string;
    bbox: { x: number; y: number; width: number; height: number };
    confidence: number;
  }>;
  /** OCR text (if available). */
  visibleText?: string;
  /** Previous action taken. */
  previousAction?: string;
}

/** Configuration for the planner. */
export interface PlannerConfig {
  /** Maximum steps per plan. */
  maxSteps: number;
  /** Maximum retries per step. */
  maxRetriesPerStep: number;
  /** Maximum plan regenerations. */
  maxReplans: number;
  /** Whether to use CNN context in planning. */
  useCNNContext: boolean;
  /** Whether to use OCR context in planning. */
  useOCRContext: boolean;
  /** Minimum confidence to proceed with a step. */
  minStepConfidence: number;
  /** Verification delay (ms) after each step. */
  verificationDelayMs: number;
}

/** Sensible defaults. */
export const DEFAULT_PLANNER_CONFIG: PlannerConfig = {
  maxSteps: 20,
  maxRetriesPerStep: 3,
  maxReplans: 3,
  useCNNContext: true,
  useOCRContext: true,
  minStepConfidence: 0.5,
  verificationDelayMs: 2000,
};

/** Events emitted by the planner for UI updates. */
export type PlannerEvent =
  | { type: 'plan_created'; plan: TaskPlan }
  | { type: 'step_started'; stepIndex: number; step: TaskStep }
  | { type: 'step_completed'; stepIndex: number; step: TaskStep }
  | { type: 'step_failed'; stepIndex: number; step: TaskStep; error: string }
  | { type: 'plan_completed'; plan: TaskPlan }
  | { type: 'plan_failed'; plan: TaskPlan; reason: string }
  | { type: 'replanning'; plan: TaskPlan; reason: string }
  | { type: 'checkpoint_saved'; stepIndex: number };
